language: python
python:
  - "3.5"
  - "3.6"
sudo: required
services:
  - docker
dist: trusty
before_install:
  - pip install pillow
install:
script:
before_deploy:
  - sudo apt-get update -qy
  - sudo apt-get install -qy python3 python3-pip
  - python3 -m pip install packagecore
  - packagecore -o dist/ "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api-key:
    secure: ARQwy2cGxVnkS+dZ+GdrwIqlGflCYD+Po3M1JGuD+lkdxfLm8J44bCjUGY/Dt28UxqJuQkqxCPb0rG5fpvCGmHUXswf1nYXQcUY6CUZEVmR8x0+z6gMFZt4iHhYTJbNO9qb7pjHBfxd1ZlWJVoiomyoZt8Mz1dVeMdFsVTiJyQt9Y+4JCrvdCWKPqf6CcnDzq0iKn7Ng+LgBqXRtJ9E24yih/VMbu5LgtScB66Hnu9ztxYBuLTw8CCnYjGyfIl8L3OD+OtGvOaBPLcE0iXfbF61dfI+qki8chP08coi7ZyJZlJ+XNaPgSBIf0JIfwSODNUC7GXm4P5uML5yU5992XbVJsVpFXcxC+4z/104+V6jMeDoEMWteBDxoRRn0gfU+lij/Eh8h40jQZGze1AdxfryYkWXyt6mG1eVc6bhjKShgJXKB1S9DlxSeN9hXs3LbftQIHBt4WMTAaR6cH2WrSDNDriqUaTjp9yhrh7t6oePTAc4Vx3/VaDQCR5CybTLeeww3wDhECgMgO5puCoixLrDiZKpfxBubKqMvDndxr5qZwMWTgkRT4CzXX3fquZfUbeD5uETB3KVRGMWv0NiM2Jv97TO6bWZr2qIqp8QcfNNjocNxI4PakorwH3eZlZKjUXl3/BWjcPh7YXIkQa5h4MNe20cEP5iOvhf/+XQUcLY=
  file_glob: true
  file:
    - dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: jarun/imgp
    python: "3.6"
